import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Header from '@/components/shared/Header'
import Section1 from '@/components/home/Section1'
import Section2 from '@/components/home/Section2'
import Websites from '@/components/home/Websites'
import Advantages from '@/components/home/Advantages'
import Product from '@/components/home/Product'
import Footer from '@/components/shared/Footer'
import Messenger from '@/components/home/Messenger'
import Stacks from '@/components/home/Stacks'
import Projects from '@/components/home/Projects'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Azart tech</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className='lines'>
          <Header/>
          <Section1/>
        </div>
        <Section2/>
        <Websites/>
        <Advantages/>
        <Product/>
        <Stacks/>
        <Messenger/>
        <Projects/>


        <Footer/>
      </main>
    </>
  )
}
